version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: realworld-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
#    depends_on:
#      - frontend
    networks:
      - my_network
      
networks:
  my_network:



